server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://111.231.117.212:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: liqing
    driver-class-name: com.mysql.jdbc.Driver